/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author PC
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private String codigoCaptcha;
private final negocio.LoginNegocio loginNegocio = new negocio.LoginNegocio();
private final java.util.Random random = new java.util.Random();

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    System.out.println(">>> L&F: " + UIManager.getLookAndFeel().getName());

    setLocationRelativeTo(null);
    generarCaptcha();
    setVisible(true);
    }
private void generarCaptcha() {
    int numero = random.nextInt(1_000_000);          // 0 a 999999
    codigoCaptcha = String.format("%06d", numero);   // siempre 6 dígitos

    // Separa los dígitos con espacios para que se lean mejor
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < codigoCaptcha.length(); i++) {
        sb.append(codigoCaptcha.charAt(i));
        if (i < codigoCaptcha.length() - 1) sb.append(' ');
    }
    lblCaptcha.setText(sb.toString());

    // Limpia el campo de captcha
    txtCaptcha.setText("");
}
private boolean validarCaptcha() {
    return txtCaptcha.getText().trim().equals(codigoCaptcha);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        lblCaptcha = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Código:");

        lblCaptcha.setText("jLabel6");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86)
                                .addComponent(lblCaptcha))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtPassword)
                                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaptcha)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnIngresar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       // 1) Capturar datos del formulario
    String usuario  = txtUsuario.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    String captcha  = txtCaptcha.getText().trim();

    // 2) Validar que no haya campos vacíos (NO regenera captcha)
    if (usuario.isEmpty() || password.isEmpty() || captcha.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Complete todos los campos, incluido el código.",
                "Campos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3) Validar captcha ANTES de consultar la BD
    if (!validarCaptcha()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "El código ingresado no es correcto.",
                "Código incorrecto",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        generarCaptcha();
        return;
    }

    // 4) Validar credenciales contra la base de datos
    entidad.Usuario u = loginNegocio.validar(usuario, password);

    if (u == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Usuario o contraseña incorrectos.",
                "Acceso denegado",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        generarCaptcha();
        txtPassword.setText("");
        return;
    }

    // 5) Credenciales correctas → guardar sesión
    config.SesionUsuario.setUsuario(u);

    // 6) Mostrar bienvenida
    javax.swing.JOptionPane.showMessageDialog(this,
            "Bienvenido, " + u.getNombreCompleto(),
            "Acceso concedido",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    // 7) Redirigir según el ROL
    String rol = u.getRol();

    if ("ADMIN".equalsIgnoreCase(rol)) {
        new presentacion.MenuAdmin().setVisible(true);
    } else if ("MECANICO".equalsIgnoreCase(rol)) {
        new presentacion.MenuMecanico().setVisible(true);
    } else if ("EMPLEADO".equalsIgnoreCase(rol)) {
        new presentacion.MenuEmpleado().setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Rol no reconocido: " + rol,
                "Error de configuración",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        config.SesionUsuario.cerrarSesion();
        generarCaptcha();
        return;
    }

    // 8) Cerrar el login
    this.dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCaptcha;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
