/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.admin.reportes;
import negocio.ReporteDAO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author PC
 */
public class pnlRepuestos extends javax.swing.JPanel {
private final ReporteDAO reporteDAO = new ReporteDAO();
    /**
     * Creates new form pnlRepuestos
     */
    public pnlRepuestos() {
        initComponents();
         configurarTabla();
    configurarFechasPorDefecto();
    cargarReporte();
    }
private void configurarTabla() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"#", "Código", "Repuesto", "Cantidad", "Ingresos"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tblDatos.setModel(modelo);

    tblDatos.getColumnModel().getColumn(0).setPreferredWidth(40);
    tblDatos.getColumnModel().getColumn(1).setPreferredWidth(90);
    tblDatos.getColumnModel().getColumn(2).setPreferredWidth(250);
    tblDatos.getColumnModel().getColumn(3).setPreferredWidth(120);
    tblDatos.getColumnModel().getColumn(4).setPreferredWidth(120);

    tblDatos.setRowHeight(25);
}

private void configurarFechasPorDefecto() {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    java.util.Calendar cal = java.util.Calendar.getInstance();

    txtHasta.setText(sdf.format(cal.getTime()));

    cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
    txtDesde.setText(sdf.format(cal.getTime()));
}
private void cargarReporte() {
    String desde = txtDesde.getText().trim();
    String hasta = txtHasta.getText().trim();

    if (desde.isEmpty() || hasta.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ingrese las fechas (formato yyyy-MM-dd).");
        return;
    }

    java.util.List<Object[]> datos = reporteDAO.reporteRepuestos(desde, hasta);

    javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tblDatos.getModel();
    modelo.setRowCount(0);

    int totalCantidad = 0;
    double totalIngresos = 0;
    int contador = 1;

    for (Object[] fila : datos) {
        modelo.addRow(new Object[]{
            contador++,
            fila[0],                                        // codigo
            fila[1],                                        // nombre
            fila[2],                                        // cantidad
            String.format("S/ %.2f", (Double) fila[3])      // ingresos
        });
        totalCantidad += (Integer) fila[2];
        totalIngresos += (Double) fila[3];
    }

    lblResumen.setText("Total repuestos vendidos: " + totalCantidad
                     + "   ·   Ingresos: S/ "
                     + String.format("%.2f", totalIngresos));

    cargarGrafico(datos);
}
private void cargarGrafico(java.util.List<Object[]> datos) {
    DefaultPieDataset dataset = new DefaultPieDataset();

    // Mostrar solo los top 6 para no saturar el pastel
    int limite = Math.min(datos.size(), 6);
    double otrosTotal = 0;
    int otrosCant = 0;

    for (int i = 0; i < datos.size(); i++) {
        Object[] fila = datos.get(i);
        String repuesto = (String) fila[1];
        int cantidad = (Integer) fila[2];

        if (i < limite) {
            dataset.setValue(repuesto + " (" + cantidad + ")", cantidad);
        } else {
            otrosCant += cantidad;
        }
    }

    if (otrosCant > 0) {
        dataset.setValue("Otros (" + otrosCant + ")", otrosCant);
    }

    JFreeChart chart = ChartFactory.createPieChart(
        "Repuestos más vendidos",
        dataset,
        true,    // mostrar leyenda
        true,    // mostrar tooltips
        false    // no URLs
    );

    chart.setBackgroundPaint(java.awt.Color.WHITE);

    ChartPanel chartPanel = new ChartPanel(chart);

    pnlGrafico.removeAll();
    pnlGrafico.setLayout(new java.awt.BorderLayout());
    pnlGrafico.add(chartPanel, java.awt.BorderLayout.CENTER);
    pnlGrafico.revalidate();
    pnlGrafico.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrafico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        lblResumen = new javax.swing.JLabel();
        btnMes = new javax.swing.JButton();
        btnHoy = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtHasta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        lblResumen.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblResumen.setText("Total: 0");

        btnMes.setText("Este mes");
        btnMes.addActionListener(this::btnMesActionPerformed);

        btnHoy.setText("Hoy");
        btnHoy.addActionListener(this::btnHoyActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        txtHasta.setText("fecha formato yyyy-MM-dd");

        btnBuscar.setText("🔍 Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel2.setText("Hasta :");

        txtDesde.setText("fecha formato yyyy-MM-dd");

        jLabel1.setText("Desde :");

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 255));
        lblTitulo.setText("REPUESTOS MÁS VENDIDOS ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(btnHoy)
                                .addGap(27, 27, 27)
                                .addComponent(btnMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(lblResumen)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoy)
                    .addComponent(btnMes)
                    .addComponent(btnLimpiar))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(lblResumen)
                        .addGap(47, 47, 47))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesActionPerformed
        configurarFechasPorDefecto();
        cargarReporte();
    }//GEN-LAST:event_btnMesActionPerformed

    private void btnHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoyActionPerformed
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String hoy = sdf.format(new java.util.Date());
        txtDesde.setText(hoy);
        txtHasta.setText(hoy);
        cargarReporte();
    }//GEN-LAST:event_btnHoyActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiar la tabla y el gráfico
        javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tblDatos.getModel();
        modelo.setRowCount(0);

        pnlGrafico.removeAll();
        pnlGrafico.revalidate();
        pnlGrafico.repaint();

        lblResumen.setText("Total: 0");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cargarReporte();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHoy;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
