/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion.empleado;

/**
 *
 * @author PC
 */
public class OrdenFormDialog extends javax.swing.JDialog {
    

    private entidad.OrdenTrabajo ordenActual;
   private final negocio.OrdenDAO ordenDAO = new negocio.OrdenDAO();
private final negocio.DetalleOrdenDAO detalleDAO = new negocio.DetalleOrdenDAO();
private final negocio.ClienteDAO clienteDAO = new negocio.ClienteDAO();
private final negocio.VehiculoDAO vehiculoDAO = new negocio.VehiculoDAO();
private final negocio.UsuarioDAO usuarioDAO = new negocio.UsuarioDAO();
private final negocio.RepuestoDAO repuestoDAO = new negocio.RepuestoDAO();

private final java.util.List<entidad.Cliente>  clientesCombo  = new java.util.ArrayList<>();
private final java.util.List<entidad.Vehiculo> vehiculosCombo = new java.util.ArrayList<>();
private final java.util.List<entidad.Usuario>  mecanicosCombo = new java.util.ArrayList<>();
private final java.util.List<entidad.Repuesto> repuestosCombo = new java.util.ArrayList<>();
private final java.util.List<entidad.DetalleOrden> itemsActuales = new java.util.ArrayList<>();
    public OrdenFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
public OrdenFormDialog(java.awt.Frame parent, entidad.OrdenTrabajo orden) {
        super(parent, true);
        initComponents();
        this.ordenActual = orden;
        setLocationRelativeTo(parent);
        setTitle(orden == null ? "Nueva Orden" : "Editar Orden - " + orden.getNumeroOrden());
          configurarTablaDetalle();
    cargarCombos();
    configurarEstadoInicial();

    if (orden == null) {
        // NUEVA ORDEN → preparar formulario vacío
        prepararNuevaOrden();
    } else {
        // EDITAR ORDEN → cargar datos
        cargarOrdenEnFormulario(orden);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtProblema = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblMecanico = new javax.swing.JLabel();
        lblObservacion = new javax.swing.JLabel();
        lblDiagnostico = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        lblProblema = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        cboMecanico = new javax.swing.JComboBox<>();
        cboCliente = new javax.swing.JComboBox<>();
        lblCliente = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cboVehiculo = new javax.swing.JComboBox<>();
        lblVehiculo1 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblTipoItem = new javax.swing.JLabel();
        cboTipoItem = new javax.swing.JComboBox<>();
        lblRepuesto = new javax.swing.JLabel();
        cboRepuesto = new javax.swing.JComboBox<>();
        lblDescripcionItem = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtDescripcionItem = new javax.swing.JTextField();
        lblPrecioItem = new javax.swing.JLabel();
        txtPrecioItem = new javax.swing.JTextField();
        btnAgregarItem = new javax.swing.JButton();
        btnQuitarItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 255));
        lblTitulo.setText("NUEVA ORDEN / EDITAR ORDEN");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblId.setText("id");

        lblFecha.setText("Fecha:");

        lblMecanico.setText("Mecánico:");

        lblObservacion.setText("Observación:");

        lblDiagnostico.setText("Diagnóstico:");

        txtId.setBackground(new java.awt.Color(255, 255, 204));
        txtId.setEnabled(false);

        txtNumero.setBackground(new java.awt.Color(255, 255, 204));
        txtNumero.setEnabled(false);

        txtFecha.setBackground(new java.awt.Color(255, 255, 204));
        txtFecha.setEnabled(false);

        lblProblema.setText("Problema:");

        lblNumero.setText("N°:");

        cboMecanico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMecanico.addActionListener(this::cboMecanicoActionPerformed);

        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCliente.addActionListener(this::cboClienteActionPerformed);

        lblCliente.setText("Cliente:");

        lblEstado.setText("Estado:");

        cboVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVehiculo1.setText("Vehículo:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCliente))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProblema)
                                    .addComponent(lblDiagnostico)
                                    .addComponent(lblMecanico))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNumero))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboCliente, 0, 202, Short.MAX_VALUE)
                                            .addComponent(cboMecanico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFecha))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstado)
                                        .addComponent(lblVehiculo1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(txtProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(txtDiagnostico)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblObservacion)))
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehiculo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCliente)
                        .addComponent(cboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMecanico)
                    .addComponent(cboMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProblema)
                    .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiagnostico)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservacion)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        lblTipoItem.setText("Tipo:");

        cboTipoItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipoItem.addActionListener(this::cboTipoItemActionPerformed);

        lblRepuesto.setText("Repuesto:");

        cboRepuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRepuesto.addActionListener(this::cboRepuestoActionPerformed);

        lblDescripcionItem.setText("Descripción:");

        lblCantidad.setText("Cantidad");

        lblPrecioItem.setText("Precio:");

        txtPrecioItem.setBackground(new java.awt.Color(204, 255, 204));
        txtPrecioItem.setEnabled(false);

        btnAgregarItem.setText("+ Agregar");
        btnAgregarItem.addActionListener(this::btnAgregarItemActionPerformed);

        btnQuitarItem.setText("- Quitar");
        btnQuitarItem.addActionListener(this::btnQuitarItemActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCantidad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcionItem)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDescripcionItem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45)
                                        .addComponent(lblPrecioItem))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblTipoItem)
                                        .addGap(32, 32, 32)
                                        .addComponent(cboTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblRepuesto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecioItem)
                                    .addComponent(cboRepuesto, 0, 127, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnAgregarItem)
                .addGap(58, 58, 58)
                .addComponent(btnQuitarItem)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoItem)
                    .addComponent(cboTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRepuesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionItem)
                    .addComponent(txtDescripcionItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioItem)
                    .addComponent(txtPrecioItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarItem)
                    .addComponent(btnQuitarItem))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        lblTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTotal.setText("TOTAL: S/ 0.00");

        btnGuardar.setText("💾 Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lblTotal))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addGap(287, 287, 287)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// ============================================================
// CONFIGURAR TABLA DE DETALLE
// ============================================================
private void configurarTablaDetalle() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Tipo", "Descripción", "Cantidad", "P. Unit", "Subtotal"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tblDetalle.setModel(modelo);

    tblDetalle.getColumnModel().getColumn(0).setPreferredWidth(90);
    tblDetalle.getColumnModel().getColumn(1).setPreferredWidth(300);
    tblDetalle.getColumnModel().getColumn(2).setPreferredWidth(70);
    tblDetalle.getColumnModel().getColumn(3).setPreferredWidth(90);
    tblDetalle.getColumnModel().getColumn(4).setPreferredWidth(100);

    tblDetalle.setRowHeight(25);
}

// ============================================================
// CARGAR COMBOS
// ============================================================
private void cargarCombos() {
    // Estados
    cboEstado.removeAllItems();
    cboEstado.addItem("PENDIENTE");
    cboEstado.addItem("EN_PROCESO");
    cboEstado.addItem("FINALIZADO");


    // Tipos de ítem
    cboTipoItem.removeAllItems();
    cboTipoItem.addItem("REPUESTO");
    cboTipoItem.addItem("MANO_OBRA");

    // Clientes
    cboCliente.removeAllItems();
    clientesCombo.clear();
    for (entidad.Cliente c : clienteDAO.listar()) {
        clientesCombo.add(c);
        cboCliente.addItem(c.toString());
    }

    // Mecánicos
    cboMecanico.removeAllItems();
    mecanicosCombo.clear();
    cboMecanico.addItem("-- Sin asignar --");
    mecanicosCombo.add(null);
    for (entidad.Usuario u : usuarioDAO.buscarMecanicos()) {
        mecanicosCombo.add(u);
        cboMecanico.addItem(u.getNombreCompleto());
    }

    // Repuestos
    cboRepuesto.removeAllItems();
    repuestosCombo.clear();
    for (entidad.Repuesto r : repuestoDAO.listar()) {
        repuestosCombo.add(r);
        cboRepuesto.addItem(r.getCodigo() + " - " + r.getNombre());
    }
}

private void configurarEstadoInicial() {
    cboTipoItem.setSelectedItem("REPUESTO");
}

// ============================================================
// PREPARAR NUEVA ORDEN
// ============================================================
private void prepararNuevaOrden() {
    txtId.setText("");
    txtNumero.setText(ordenDAO.obtenerSiguienteNumero());
    txtFecha.setText(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm").format(new java.util.Date()));
    txtProblema.setText("");
    txtDiagnostico.setText("");
    txtObservacion.setText("");

    if (cboCliente.getItemCount() > 0) cboCliente.setSelectedIndex(0);
    if (cboMecanico.getItemCount() > 0) cboMecanico.setSelectedIndex(0);
    cboEstado.setSelectedItem("PENDIENTE");

    itemsActuales.clear();
    refrescarTablaDetalle();
    actualizarTotal();

    txtProblema.requestFocus();
}

// ============================================================
// CARGAR ORDEN EN FORMULARIO
// ============================================================
private void cargarOrdenEnFormulario(entidad.OrdenTrabajo o) {
    txtId.setText(String.valueOf(o.getId()));
    txtNumero.setText(o.getNumeroOrden());
    txtFecha.setText(o.getFechaIngreso() != null ? o.getFechaIngreso() : "");
    txtProblema.setText(o.getDescripcionProblema() != null ? o.getDescripcionProblema() : "");
    txtDiagnostico.setText(o.getDiagnostico() != null ? o.getDiagnostico() : "");
    txtObservacion.setText(o.getObservacion() != null ? o.getObservacion() : "");
    cboEstado.setSelectedItem(o.getEstado());

    // Cliente
    for (int i = 0; i < clientesCombo.size(); i++) {
        if (clientesCombo.get(i).getId() == o.getClienteId()) {
            cboCliente.setSelectedIndex(i);
            break;
        }
    }

    // Vehículo (depende del cliente)
    cargarVehiculosDelCliente();
    for (int i = 0; i < vehiculosCombo.size(); i++) {
        if (vehiculosCombo.get(i).getId() == o.getVehiculoId()) {
            cboVehiculo.setSelectedIndex(i);
            break;
        }
    }

    // Mecánico
    for (int i = 0; i < mecanicosCombo.size(); i++) {
        entidad.Usuario u = mecanicosCombo.get(i);
        if (u != null && u.getId() == o.getMecanicoId()) {
            cboMecanico.setSelectedIndex(i);
            break;
        }
    }

    // Cargar detalle desde BD
    itemsActuales.clear();
    itemsActuales.addAll(detalleDAO.listarPorOrden(o.getId()));
    refrescarTablaDetalle();
    actualizarTotal();
}

// ============================================================
// CARGAR VEHÍCULOS SEGÚN CLIENTE
// ============================================================
private void cargarVehiculosDelCliente() {
    cboVehiculo.removeAllItems();
    vehiculosCombo.clear();

    int idx = cboCliente.getSelectedIndex();
    if (idx < 0) return;

    entidad.Cliente c = clientesCombo.get(idx);
    for (entidad.Vehiculo v : vehiculoDAO.listar()) {
        if (v.getClienteId() == c.getId()) {
            vehiculosCombo.add(v);
            cboVehiculo.addItem(v.getPlaca() + " - " + v.getMarca() + " " + v.getModelo());
        }
    }
}

// ============================================================
// REFRESCAR TABLA DE DETALLE
// ============================================================
private void refrescarTablaDetalle() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblDetalle.getModel();
    modelo.setRowCount(0);

    for (entidad.DetalleOrden d : itemsActuales) {
        modelo.addRow(new Object[]{
            d.getTipoItem(),
            d.getDescripcion(),
            d.getCantidad(),
            String.format("%.2f", d.getPrecioUnitario()),
            String.format("%.2f", d.getSubtotal())
        });
    }
}

// ============================================================
// ACTUALIZAR TOTAL
// ============================================================
private void actualizarTotal() {
    double total = 0;
    for (entidad.DetalleOrden d : itemsActuales) {
        total += d.getSubtotal();
    }
    lblTotal.setText(String.format("TOTAL: S/ %.2f", total));
}
    private void cboMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMecanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMecanicoActionPerformed

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
       cargarVehiculosDelCliente();
    }//GEN-LAST:event_cboClienteActionPerformed

    private void cboTipoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoItemActionPerformed
       String tipo = (String) cboTipoItem.getSelectedItem();
    if ("REPUESTO".equals(tipo)) {
        cboRepuesto.setEnabled(true);
        txtDescripcionItem.setEditable(true);
        txtPrecioItem.setEditable(true);
    } else {
        cboRepuesto.setEnabled(false);
        cboRepuesto.setSelectedIndex(-1);
        txtDescripcionItem.setText("");
        txtDescripcionItem.setEditable(true);
        txtPrecioItem.setText("");
        txtPrecioItem.setEditable(true);
    }
    }//GEN-LAST:event_cboTipoItemActionPerformed

    private void cboRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRepuestoActionPerformed
        int idx = cboRepuesto.getSelectedIndex();
    if (idx < 0) return;

    entidad.Repuesto r = repuestosCombo.get(idx);
    txtDescripcionItem.setText(r.getNombre());
    txtPrecioItem.setText(String.format("%.2f", r.getPrecioVenta()));

    if (txtCantidad.getText().trim().isEmpty()) {
        txtCantidad.setText("1");
    }
    txtCantidad.requestFocus();
    txtCantidad.selectAll();
    }//GEN-LAST:event_cboRepuestoActionPerformed

    private void btnAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarItemActionPerformed
        String tipo = (String) cboTipoItem.getSelectedItem();
    String descripcion = txtDescripcionItem.getText().trim();
    String cantStr = txtCantidad.getText().trim();

    // Validaciones básicas
    if (descripcion.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una descripción.");
        return;
    }
    if (cantStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese la cantidad.");
        return;
    }

    int cantidad;
    try {
        cantidad = Integer.parseInt(cantStr);
        if (cantidad <= 0) throw new NumberFormatException();
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número mayor a 0.");
        return;
    }

    // Precio: se toma del repuesto si es REPUESTO, o del campo si es MANO_OBRA
    double precio;

    if ("REPUESTO".equals(tipo)) {
        int idx = cboRepuesto.getSelectedIndex();
        if (idx < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un repuesto.");
            return;
        }
        // ✅ Precio directo del objeto Repuesto (sin parsing)
        precio = repuestosCombo.get(idx).getPrecioVenta();
    } else {
        // MANO_OBRA: leer del campo, forzando coma → punto si es necesario
        String precStr = txtPrecioItem.getText().trim().replace(",", ".");
        if (precStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el precio.");
            return;
        }
        try {
            precio = Double.parseDouble(precStr);
            if (precio < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El precio debe ser un número mayor o igual a 0.\nValor leído: '" + precStr + "'");
            return;
        }
    }

    // Construir ítem
    entidad.DetalleOrden d = new entidad.DetalleOrden();
    d.setTipoItem(tipo);
    d.setDescripcion(descripcion);
    d.setCantidad(cantidad);
    d.setPrecioUnitario(precio);
    d.calcularSubtotal();

    if ("REPUESTO".equals(tipo)) {
        int idx = cboRepuesto.getSelectedIndex();
        d.setRepuestoId(repuestosCombo.get(idx).getId());
    }

    itemsActuales.add(d);
    refrescarTablaDetalle();
    actualizarTotal();

    // Limpiar
    txtDescripcionItem.setText("");
    txtCantidad.setText("");
    txtPrecioItem.setText("");
    if ("REPUESTO".equals(tipo)) {
        cboRepuesto.setSelectedIndex(-1);
    }
    txtDescripcionItem.requestFocus();
    }//GEN-LAST:event_btnAgregarItemActionPerformed

    private void btnQuitarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarItemActionPerformed
        int fila = tblDetalle.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un ítem para quitar.");
        return;
    }

    int r = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Quitar este ítem de la orden?", "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (r == javax.swing.JOptionPane.YES_OPTION) {
        itemsActuales.remove(fila);
        refrescarTablaDetalle();
        actualizarTotal();
    }
    }//GEN-LAST:event_btnQuitarItemActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       // Validaciones
    if (cboCliente.getSelectedIndex() < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
        return;
    }
    if (cboVehiculo.getSelectedIndex() < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un vehículo.");
        return;
    }
    if (txtProblema.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el problema reportado.");
        return;
    }
    if (itemsActuales.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Agregue al menos un ítem al detalle.");
        return;
    }

    // Calcular total
    double total = 0;
    for (entidad.DetalleOrden d : itemsActuales) {
        total += d.getSubtotal();
    }

    // Construir orden
    entidad.OrdenTrabajo o = new entidad.OrdenTrabajo();
    o.setNumeroOrden(txtNumero.getText());
    o.setClienteId(clientesCombo.get(cboCliente.getSelectedIndex()).getId());
    o.setVehiculoId(vehiculosCombo.get(cboVehiculo.getSelectedIndex()).getId());

    int idxMec = cboMecanico.getSelectedIndex();
    entidad.Usuario mec = (idxMec > 0) ? mecanicosCombo.get(idxMec) : null;
    o.setMecanicoId(mec != null ? mec.getId() : 0);

    o.setDescripcionProblema(txtProblema.getText().trim());
    o.setDiagnostico(txtDiagnostico.getText().trim());
    o.setEstado((String) cboEstado.getSelectedItem());
    o.setTotal(total);
    o.setObservacion(txtObservacion.getText().trim());
    o.setActivo(1);

    if (ordenActual == null) {
        // INSERTAR
        int id = ordenDAO.insertar(o);
        if (id <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo insertar la orden.");
            return;
        }
        // Insertar detalle
        for (entidad.DetalleOrden d : itemsActuales) {
            d.setOrdenId(id);
            detalleDAO.insertar(d);
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Orden registrada: " + o.getNumeroOrden());
    } else {
        // ACTUALIZAR
        o.setId(ordenActual.getId());
        o.setFechaEntrega(ordenActual.getFechaEntrega());
        if (!ordenDAO.actualizar(o)) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo actualizar la orden.");
            return;
        }
        // Borrar detalle anterior e insertar el nuevo
        detalleDAO.eliminarPorOrden(o.getId());
        for (entidad.DetalleOrden d : itemsActuales) {
            d.setOrdenId(o.getId());
            detalleDAO.insertar(d);
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Orden actualizada.");
    }

    dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       int r = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Cancelar? Los cambios no se guardarán.",
        "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

    if (r == javax.swing.JOptionPane.YES_OPTION) {
        dispose();
    }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                OrdenFormDialog dialog = new OrdenFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarItem;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitarItem;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboMecanico;
    private javax.swing.JComboBox<String> cboRepuesto;
    private javax.swing.JComboBox<String> cboTipoItem;
    private javax.swing.JComboBox<String> cboVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescripcionItem;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMecanico;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblPrecioItem;
    private javax.swing.JLabel lblProblema;
    private javax.swing.JLabel lblRepuesto;
    private javax.swing.JLabel lblTipoItem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVehiculo1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcionItem;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPrecioItem;
    private javax.swing.JTextField txtProblema;
    // End of variables declaration//GEN-END:variables
}
