/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.empleado;

/**
 *
 * @author PC
 */
public class RepuestoPanel extends javax.swing.JPanel {
private final negocio.RepuestoDAO repuestoDAO = new negocio.RepuestoDAO();
    /**
     * Creates new form RepuestoPanel
     */
    public RepuestoPanel() {
        initComponents();
        cargarTabla();
    }
private void cargarTabla() {
    java.util.List<entidad.Repuesto> lista;

    if (chkMostrarInactivos.isSelected()) {
        lista = repuestoDAO.listarTodos();
    } else {
        lista = repuestoDAO.listar();
    }

    llenarTabla(lista);
}

private void llenarTabla(java.util.List<entidad.Repuesto> lista) {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"ID", "Código", "Nombre", "Descripción", "Stock", "Mínimo", "P. Venta", "Estado"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;   // todo solo lectura
        }
    };

    int stockBajo = 0;

    for (entidad.Repuesto r : lista) {
        String estado = (r.getActivo() == 1) ? "Activo" : "Inactivo";
        if (r.isStockBajo() && r.getActivo() == 1) stockBajo++;

        modelo.addRow(new Object[]{
            r.getId(),
            r.getCodigo(),
            r.getNombre(),
            r.getDescripcion(),
            r.getStock(),
            r.getStockMinimo(),
            String.format("S/ %.2f", r.getPrecioVenta()),
            estado
        });
    }

    tblRepuestos.setModel(modelo);

    // Anchos
    tblRepuestos.getColumnModel().getColumn(0).setPreferredWidth(40);
    tblRepuestos.getColumnModel().getColumn(1).setPreferredWidth(80);
    tblRepuestos.getColumnModel().getColumn(2).setPreferredWidth(180);
    tblRepuestos.getColumnModel().getColumn(3).setPreferredWidth(220);
    tblRepuestos.getColumnModel().getColumn(4).setPreferredWidth(60);
    tblRepuestos.getColumnModel().getColumn(5).setPreferredWidth(60);
    tblRepuestos.getColumnModel().getColumn(6).setPreferredWidth(80);
    tblRepuestos.getColumnModel().getColumn(7).setPreferredWidth(80);

    tblRepuestos.setRowHeight(25);

    // Aplicar color a las filas con stock bajo
    tblRepuestos.setDefaultRenderer(Object.class, new StockBajoRenderer());

    // Actualizar contador
    lblInfo.setText("Total repuestos: " + lista.size()
                  + "   ·   Stock bajo: " + stockBajo + " ⚠️");
}
private void buscarRepuestos() {
    String texto = txtBuscar.getText().trim();
    java.util.List<entidad.Repuesto> lista;

    if (texto.isEmpty()) {
        if (chkMostrarInactivos.isSelected()) lista = repuestoDAO.listarTodos();
        else lista = repuestoDAO.listar();
    } else {
        if (chkMostrarInactivos.isSelected()) lista = repuestoDAO.buscarTodos(texto);
        else lista = repuestoDAO.buscar(texto);
    }

    llenarTabla(lista);
}
    private class StockBajoRenderer extends javax.swing.table.DefaultTableCellRenderer {
        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            java.awt.Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            // Obtener stock y mínimo de esa fila
            int stock = Integer.parseInt(table.getValueAt(row, 4).toString());
            int minimo = Integer.parseInt(table.getValueAt(row, 5).toString());

            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
                c.setForeground(table.getSelectionForeground());
            } else if (stock <= minimo) {
                c.setBackground(new java.awt.Color(255, 220, 220));  // rojo claro
                c.setForeground(java.awt.Color.BLACK);
            } else {
                c.setBackground(table.getBackground());
                c.setForeground(table.getForeground());
            }
            return c;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        chkMostrarInactivos = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepuestos = new javax.swing.JTable();
        lblInfo = new javax.swing.JLabel();

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 255));
        lblTitulo.setText("INVENTARIO DE REPUESTOS");

        lblBuscar.setText("buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        chkMostrarInactivos.setText("Mostrar Inactivos");
        chkMostrarInactivos.addItemListener(this::chkMostrarInactivosItemStateChanged);

        tblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRepuestos);

        lblInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblInfo.setText("Total: X · Stock bajo: Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblBuscar)
                        .addGap(81, 81, 81)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(chkMostrarInactivos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfo))
                            .addComponent(lblTitulo))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMostrarInactivos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
          if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        buscarRepuestos();
    }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void chkMostrarInactivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkMostrarInactivosItemStateChanged
       buscarRepuestos();
    }//GEN-LAST:event_chkMostrarInactivosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkMostrarInactivos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblRepuestos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
